# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:title/
relative_permalinks: true

# Setup
title:               Relatively Ignorant
description:         'A blog on things about which I may or may not know things'
paginate:            5
baseurl:             'https://mjstrasser.github.io/'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Michael Strasser
  url:               https://michaelstrasser.com/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
