permalink:           /:year/:month/:title/

title:               Relatively Ignorant
description:         'A blog on things about which I may or may not know stuff'
paginate:            5

exclude: [".gitignore", "CNAME", "README.md"]

author:
  name:              Michael Strasser
  url:               https://michaelstrasser.com/

version:             2.0.0
